package generator;

import com.seedfinding.mccore.util.pos.CPos;
import dev.xpple.cubiomes.*;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;

/*
The blocks of a square of chunks that caves and ravines carved out (carved blocks at Y<=10 are lava, the rest air),
or that hold water from the terrain or the underwater carvers, and the height of the ground before carving.
 */
public class CarveRegion {
    private static final int CHUNK_BITS = 16 * 16 * 256;
    private static final int SEA_LEVEL = 63;

    private final int minChunkX;
    private final int minChunkZ;
    private final int width;
    private final long[][] carved;
    // water, allocated per chunk when needed
    private final long[][] water;
    // per column the first Y above the top block that isn't air or water
    private final int[] ground;

    CarveRegion(CPos center, int chunkRadius) {
        this.minChunkX = center.getX() - chunkRadius;
        this.minChunkZ = center.getZ() - chunkRadius;
        this.width = 2 * chunkRadius + 1;
        this.carved = new long[width * width][CHUNK_BITS / 64];
        this.water = new long[width * width][];
        this.ground = new int[width * width * 256];
        java.util.Arrays.fill(ground, SEA_LEVEL);
    }

    /*
    The caves and ravines as cubiomes carves them, which only needs the structure seed. Compared against deserts
    generated by the vanilla 1.17.1 server this matched the air, water, lava and solid blocks below Y=60 to ~99.7%.
    It doesn't know the terrain though: vanilla skips every piece of a cave that would touch water, so next to
    rivers and oceans this carves more than the game does (VanillaCarver doesn't have that problem). The ground
    is taken to be at sea level everywhere.
     */
    public static CarveRegion cubiomes(long structureSeed, CPos center, int chunkRadius) {
        CarveRegion region = new CarveRegion(center, chunkRadius);
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment poses = arena.allocate(Pos3List.layout());
            MemorySegment canyonConfig = arena.allocate(CanyonCarverConfig.layout());
            MemorySegment caveConfig = arena.allocate(CaveCarverConfig.layout());
            // the biomes only matter for ocean carvers, the regular cave and canyon carvers run everywhere else
            MemorySegment biomes = arena.allocate(Cubiomes.C_INT.byteSize() * 17 * 17);
            Cubiomes.getCanyonCarverConfig(Cubiomes.CANYON_CARVER(), Cubiomes.MC_1_17_1(), canyonConfig);
            Cubiomes.getCaveCarverConfig(Cubiomes.CAVE_CARVER(), Cubiomes.MC_1_17_1(), Cubiomes.desert(), caveConfig);

            for (int i = 0; i < region.width; i++) {
                for (int j = 0; j < region.width; j++) {
                    int chunkX = region.minChunkX + i;
                    int chunkZ = region.minChunkZ + j;
                    Cubiomes.createPos3List(poses, 4096);
                    Cubiomes.carveCave(structureSeed, Cubiomes.MC_1_17_1(), chunkX, chunkZ,
                            caveConfig, Cubiomes.CAVE_CARVER(), biomes, poses);
                    Cubiomes.carveCanyon(structureSeed, Cubiomes.MC_1_17_1(), chunkX, chunkZ,
                            canyonConfig, Cubiomes.CANYON_CARVER(), biomes, poses);

                    long[] bits = region.carved[i * region.width + j];
                    int size = Pos3List.size(poses);
                    MemorySegment list = Pos3List.pos3s(poses);
                    for (int k = 0; k < size; k++) {
                        MemorySegment pos = Pos3.asSlice(list, k);
                        int index = bitIndex(Pos3.x(pos), Pos3.y(pos), Pos3.z(pos));
                        bits[index >>> 6] |= 1L << index;
                    }
                    Cubiomes.freePos3List(poses);
                }
            }
        }
        return region;
    }

    public boolean isCarved(int x, int y, int z) {
        return test(carved, x, y, z);
    }

    public boolean isWater(int x, int y, int z) {
        return test(water, x, y, z);
    }

    // the first Y above the top block of the uncarved terrain that isn't air or water
    public int ground(int x, int z) {
        if (!contains(x, z)) return SEA_LEVEL;
        return ground[((x - (minChunkX << 4)) * width << 4) + z - (minChunkZ << 4)];
    }

    void setGround(int x, int z, int y) {
        if (contains(x, z)) ground[((x - (minChunkX << 4)) * width << 4) + z - (minChunkZ << 4)] = y;
    }

    void setCarved(int x, int y, int z) {
        set(carved, x, y, z, true);
        set(water, x, y, z, false);
    }

    void setWater(int x, int y, int z) {
        set(carved, x, y, z, false);
        set(water, x, y, z, true);
    }

    // a solid block that isn't part of a structure, like the obsidian underwater carvers leave at Y=10
    void setSolid(int x, int y, int z) {
        set(carved, x, y, z, false);
        set(water, x, y, z, false);
    }

    private boolean test(long[][] layer, int x, int y, int z) {
        if (y < 0 || y > 255 || !contains(x, z)) return false;
        long[] bits = layer[chunkIndex(x, z)];
        int index = bitIndex(x, y, z);
        return bits != null && (bits[index >>> 6] >>> index & 1L) != 0;
    }

    private void set(long[][] layer, int x, int y, int z, boolean value) {
        if (y < 0 || y > 255 || !contains(x, z)) return;
        int chunk = chunkIndex(x, z);
        int index = bitIndex(x, y, z);
        if (value) {
            if (layer[chunk] == null) layer[chunk] = new long[CHUNK_BITS / 64];
            layer[chunk][index >>> 6] |= 1L << index;
        } else if (layer[chunk] != null) {
            layer[chunk][index >>> 6] &= ~(1L << index);
        }
    }

    private int chunkIndex(int x, int z) {
        return ((x >> 4) - minChunkX) * width + (z >> 4) - minChunkZ;
    }

    public boolean contains(int x, int z) {
        int i = (x >> 4) - minChunkX;
        int j = (z >> 4) - minChunkZ;
        return i >= 0 && j >= 0 && i < width && j < width;
    }

    public int getMinChunkX() {
        return minChunkX;
    }

    public int getMinChunkZ() {
        return minChunkZ;
    }

    public int getWidth() {
        return width;
    }

    private static int bitIndex(int x, int y, int z) {
        return y << 8 | (z & 15) << 4 | (x & 15);
    }

    static {
        CubiomesInit.load();
    }
}
